# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-cli',
                'doc_host': 'https://pydanny.github.io',
                'git_url': 'https://github.com/pydanny/nbdev-cli',
                'lib_path': 'nbdev_cli'},
  'syms': {'nbdev_cli.core': {'nbdev_cli.core.foo': ('core.html#foo', 'nbdev_cli/core.py')}}}
