# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbz',
                'doc_host': 'https://pydanny.github.io',
                'git_url': 'https://github.com/pydanny/nbz',
                'lib_path': 'nbz'},
  'syms': { 'nbz.commands': { 'nbz.commands._delegates_sorted': ('commands.html#_delegates_sorted', 'nbz/commands.py'),
                              'nbz.commands.bump_version': ('commands.html#bump_version', 'nbz/commands.py'),
                              'nbz.commands.check': ('commands.html#check', 'nbz/commands.py'),
                              'nbz.commands.new': ('commands.html#new', 'nbz/commands.py')},
            'nbz.core': { 'nbz.core.add_nyi_command': ('core.html#add_nyi_command', 'nbz/core.py'),
                          'nbz.core.helper': ('core.html#helper', 'nbz/core.py'),
                          'nbz.core.with_spinner': ('core.html#with_spinner', 'nbz/core.py')}}}
