# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbz',
                'doc_host': 'https://pydanny.github.io',
                'git_url': 'https://github.com/pydanny/nbz',
                'lib_path': 'nbz'},
  'syms': { 'nbz.core': { 'nbz.core.add_command': ('core.html#add_command', 'nbz/core.py'),
                          'nbz.core.add_nyi_command': ('core.html#add_nyi_command', 'nbz/core.py'),
                          'nbz.core.helper': ('core.html#helper', 'nbz/core.py')}}}
