# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbz',
                'doc_host': 'https://pydanny.github.io',
                'git_url': 'https://github.com/pydanny/nbz',
                'lib_path': 'nbz'},
  'syms': {'nbz.core': {'nbz.core.foo': ('core.html#foo', 'nbz/core.py')}}}
